name: 'Wecom Notification Action'
description: '企业微信机器人消息发送，支持内容自定义，配置模版'
branding:
  icon: 'send'  
  color: 'green'
inputs:
  message:
    description: "需要发送的内容"
    required: true
  webhook:
    description: "企业微信机器人 webhook url key, 即 webhook/send?key=xxx, 配置为xxx即可"
    required: true
  is_at_all:
    description: "是否 @all @所有人?"
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Pass Inputs to Shell
      run: |
          echo "INPUT_MESSAGE=${{ inputs.message }}" >> $GITHUB_ENV
          echo "INPUT_WEBHOOK=${{ inputs.webhook }}" >> $GITHUB_ENV
          echo "INPUT_IS_AT_ALL=${{ inputs.is_at_all }}" >> $GITHUB_ENV
      shell: bash
    - name: Send notification message
      id: send-notification-message
      run: python notification.py
      shell: bash