name: wecom robot

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: wecom robot action
        uses: guangzhengli/wecom-notification-action@main
        with:
          webhook: ${{ secrets.WECOM_WEBHOOK_KEY}}
          is_at_all: "false"
          type: "file"
          message: "test content"
          file_name: "members.txt"
          file_read_type: "first"
          file_write_type: "loop"