name: wecom robot

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: wecom robot action
        uses: guangzhengli/wecom-notification-action@main
        with:
          url: ${{ secrets.WECOM_WEBHOOK_KEY}}
          is_at_all: 'false'
          message: test content